server:
  port: 8080 # Or your desired port for Configuration Service

spring:
  application:
    name: configuration-service # Important: Set the application name for Eureka registration
  datasource:
    url: jdbc:mysql://localhost:3306/vet?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true # Added createDatabaseIfNotExist
    username: root
    password: Ben@24
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true # Set to false in production
    hibernate:
      ddl-auto: update # Use 'update' for production, 'create-drop' for dev (careful with data loss!)
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # MySQL Dialect

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"

logging:
  level:
       org.springframework.security : DEBUG



